@echo off
setlocal EnableExtensions
rem ---------------------------------------------------------------------------
rem Swap the whole RTGL1 runtime between a known-good 2026-08-03 build and the
rem current one, to find where the DLSS-RR worm / black-grain regression entered.
rem
rem Why a binary swap instead of more cvar A/Bs: every cvar arm so far (guide
rem contents, guide floor, specular hit distance, disocclusion mask, mip bias,
rem blue noise, spp) came back negative, so the cause is something with no knob
rem on it. This compares two complete runtimes and cannot miss it.
rem
rem BISECT POINTS (build more with build-rtgl-variant.cmd <commit> <name>):
rem   aug03  df2797e  08-02  native NGX Vulkan DLSS-RR path      <- CONFIRMED GOOD
rem   aug04  cb067f5  08-04  Dev Materials A/B, RR live knobs, roughness matte
rem   aug05  d50bbcb  08-05  DLSS-RR, emissive mult>1, ceiling/hang lamps
rem   aug06  0683fbb  08-06  guide fixes + disocclusion mask
rem   head            08-07  current                             <- CONFIRMED BAD
rem
rem Binary search: test aug05 first. Good -> the cause is in aug06 or the 08-07
rem commits; bad -> it is in aug04 or aug05.
rem
rem   aug03 = sourcecode/gzdoom-rt/build/WashScratch/rt (2026-08-03)
rem           Predates the 08-05 guide rework, the 08-06 disocclusion mask and
rem           every 08-07 change. Verified to have RR compiled IN (it contains
rem           NVSDK_NGX_VULKAN_EvaluateFeature and the "DLSSRR: Ray
rem           Reconstruction available" string), so it is a real RR baseline and
rem           not one of the builds where RR was silently compiled out.
rem   head  = the current build
rem
rem DLL AND SHADERS ARE SWAPPED TOGETHER. This is not optional: the
rem ShGlobalUniform layout generated by GenerateShaderCommon.py has changed
rem several times since 08-03, so an old DLL driving new SPIR-V (or the reverse)
rem reads every uniform at the wrong offset and the result is meaningless.
rem
rem gzdoom.exe is NOT swapped. That is safe as long as new fields were only ever
rem APPENDED to RgDrawFrameIlluminationParams -- the old DLL then just reads the
rem prefix it knows. If the old arm looks wildly broken (crash, black screen,
rem absurd colours) rather than merely different, suspect that assumption rather
rem than trusting the comparison.
rem
rem To get back to a guaranteed-correct current runtime at any time:
rem     tools\build-rtgl.cmd
rem
rem Usage: ab-rtgl-baseline.cmd <aug03|head> [1-32]
rem ---------------------------------------------------------------------------

set "WHICH=%~1"
set "MAP=%~2"
if "%WHICH%"=="" set "WHICH=aug03"
if "%MAP%"==""  set "MAP=2"

set "SRC=%~dp0rtgl-variants\%WHICH%"
set "DST=G:\AI\Doom64-RT\sourcecode\gzdoom-rt\build\RelWithDebInfo\rt"

if not exist "%SRC%\RTGL1.dll" (
  echo Usage: %~nx0 ^<aug03^|head^> [1-32]
  echo   missing variant: %SRC%
  exit /b 1
)

echo === RTGL runtime: %WHICH%, MAP%MAP% ===
copy /Y "%SRC%\RTGL1.dll" "%DST%\bin\RTGL1.dll" >nul || exit /b 1
copy /Y "%SRC%\shaders\*.spv" "%DST%\shaders\" >nul || exit /b 1

rem -rtdebug so the DLSSRR init lines land in the log: with the old DLL we need
rem positive confirmation that RR actually initialised, otherwise a clean-looking
rem image might just be A-SVGF.
call "%~dp0launch-retribution-rt.cmd" %MAP% debug
exit /b %ERRORLEVEL%
