@echo off
setlocal enabledelayedexpansion
rem =========================================================================
rem  Builds everything the RTGL NRD lane needs, in order:
rem    1. ShaderMake            (deps\ShaderMake -> bin\Release\ShaderMake.exe)
rem    2. NRD _Shaders headers  (SPIR-V embedded via DXC; committed, so this
rem                              step only reruns when NRD shaders change)
rem    3. NRI static libs       (VK-only; deps\NRI\_Bin + BuildCMake\Release)
rem
rem  After this, tools\build-rtgl.cmd links it all -- but ONLY when
rem  D64RT_WITH_NRD=1 is set. RG_WITH_NRD now defaults OFF so a clean
rem  checkout (and CI, where deps\ does not exist) still builds the
rem  A-SVGF baseline instead of failing configure.
rem
rem  DXC: needs the GITHUB release build -- the Windows SDK dxc.exe reports
rem  "SPIR-V CodeGen not available". tools\dxc is populated from
rem  https://github.com/microsoft/DirectXShaderCompiler/releases (v1.9.2607
rem  used originally); it is gitignored, so a fresh checkout must re-download.
rem =========================================================================

set "ROOT=%~dp0.."
set "DXC=%ROOT%\tools\dxc\bin\x64\dxc.exe"

rem --- 0/3: vendor the sources if missing -------------------------------
rem deps\ is gitignored by policy (local installs only), so a fresh checkout
rem re-vendors from the local Duke-RT tree -- the working reference this
rem integration was ported from. Versions: NRD 4.17.1, NRDIntegration v21.
set "DUKE=%ROOT%\sourcecode\Duke-RT\libraries"
if not exist "%ROOT%\deps\NRD\Include\NRD.h" (
  if not exist "%DUKE%\NRD\Include\NRD.h" (
    echo ERROR: deps\NRD missing and no Duke-RT checkout to vendor from.
    exit /b 1
  )
  echo === 0/3 Vendoring NRD/NRI/MathLib/ShaderMake from Duke-RT ===
  robocopy "%DUKE%\NRD" "%ROOT%\deps\NRD" /E /NFL /NDL /NJH /NJS
  robocopy "%DUKE%\NRIFramework\External\NRI" "%ROOT%\deps\NRI" /E /NFL /NDL /NJH /NJS
  robocopy "%DUKE%\NRIFramework\External\MathLib" "%ROOT%\deps\MathLib" /E /NFL /NDL /NJH /NJS
  robocopy "%DUKE%\ShaderMake" "%ROOT%\deps\ShaderMake" /E /NFL /NDL /NJH /NJS
)

if not exist "%DXC%" (
  echo ERROR: %DXC% not found.
  echo Download the dxc_*.zip from github.com/microsoft/DirectXShaderCompiler/releases
  echo and extract it to tools\dxc ^(so that tools\dxc\bin\x64\dxc.exe exists^).
  exit /b 1
)

echo === 1/3 ShaderMake ===
cmake -S "%ROOT%\deps\ShaderMake" -B "%ROOT%\deps\ShaderMake\BuildCMake" -G "Visual Studio 17 2022" -A x64 ^
  -DSHADERMAKE_FIND_FXC=OFF -DSHADERMAKE_FIND_DXC=OFF -DSHADERMAKE_FIND_DXC_VK=OFF || exit /b 1
cmake --build "%ROOT%\deps\ShaderMake\BuildCMake" --config Release || exit /b 1

echo === 2/3 NRD _Shaders (SPIR-V, embedded headers) ===
rem NRDConfig.hlsli is normally generated by NRD's own CMake; ours is
rem hand-written and TRACKED at tools\nrd\NRDConfig.hlsli (deps\ is
rem gitignored). It must match the NRD_* compile definitions in
rem deps\RTGL\CMakeLists.txt -- see the file's header.
copy /Y "%ROOT%\tools\nrd\NRDConfig.hlsli" "%ROOT%\deps\NRD\Shaders\NRDConfig.hlsli" >nul || exit /b 1
rem The register shifts MUST stay in lockstep with three other places:
rem   deps\RTGL\CMakeLists.txt   SPIRV_*REG_OFFSET defines
rem   deps\RTGL\Source\NrdDenoiser.cpp   nri::VKBindingOffsets
rem   deps\NRD\Shaders\NRDConfig.hlsli   (hand-written; see its header)
pushd "%ROOT%\deps\NRD"
"%ROOT%\deps\ShaderMake\bin\Release\ShaderMake.exe" -p SPIRV --compiler "%DXC%" ^
  --flatten --stripReflection --WX ^
  --sRegShift 0 --bRegShift 2 --uRegShift 3 --tRegShift 20 ^
  --headerBlob --allResourcesBound --vulkanVersion 1.2 ^
  --sourceDir "Shaders" --ignoreConfigDir -c "Shaders/Shaders.cfg" ^
  -o "_Shaders" -I "%ROOT%\deps\MathLib" -D NRD_INTERNAL || (popd & exit /b 1)
popd

echo === 3/3 NRI (VK-only, SHARED) ===
rem SHARED on purpose: NRI's VK backend embeds its own VulkanMemoryAllocator
rem implementation and so does RTGL1.dll -- two static VMA TUs in one binary
rem are LNK2005 across every Vma* class. As a DLL, NRI's copy stays inside
rem NRI.dll (Duke-RT ships NRI as runtime DLLs for the same reason).
rem build-rtgl.cmd stages NRI.dll next to RTGL1.dll.
rem
rem The two FetchContent deps are pinned local clones: GitHub's archive/zip
rem endpoint rate-limits hard (429), git clone does not.
if not exist "%ROOT%\deps\NRI\External-pinned\vulkan_headers\include\vulkan\vulkan.h" (
  git clone --depth 1 --branch v1.4.344 https://github.com/KhronosGroup/Vulkan-Headers "%ROOT%\deps\NRI\External-pinned\vulkan_headers" || exit /b 1
)
if not exist "%ROOT%\deps\NRI\External-pinned\vma\include\vk_mem_alloc.h" (
  git clone https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator "%ROOT%\deps\NRI\External-pinned\vma" || exit /b 1
  pushd "%ROOT%\deps\NRI\External-pinned\vma"
  git checkout e722e57c891a8fbe3cc73ca56c19dd76be242759 || (popd & exit /b 1)
  popd
)
cmake -S "%ROOT%\deps\NRI" -B "%ROOT%\deps\NRI\BuildCMake" -G "Visual Studio 17 2022" -A x64 ^
  -DNRI_STATIC_LIBRARY=OFF -DNRI_ENABLE_D3D11_SUPPORT=OFF -DNRI_ENABLE_D3D12_SUPPORT=OFF ^
  -DNRI_ENABLE_NVTX_SUPPORT=OFF -DNRI_ENABLE_NIS_SDK=OFF -DNRI_ENABLE_IMGUI_EXTENSION=OFF ^
  "-DFETCHCONTENT_SOURCE_DIR_VULKAN_HEADERS=%ROOT%\deps\NRI\External-pinned\vulkan_headers" ^
  "-DFETCHCONTENT_SOURCE_DIR_VMA=%ROOT%\deps\NRI\External-pinned\vma" || exit /b 1
cmake --build "%ROOT%\deps\NRI\BuildCMake" --config Release || exit /b 1

echo.
echo NRD_DEPS_OK -- now run .\tools\build-rtgl.cmd
exit /b 0
