"""Turn the material labeller's `surface` field into the impact-FX surface table.

WHAT THIS CONSUMES, AND WHAT IT MUST NOT TOUCH. `tools/_material_labels/*.json`
is produced by the PBR material-labelling pipeline (`gen_material_labeller.py` ->
the labelling page -> `apply_material_labels.py`), which is owned elsewhere. That
pipeline merges `metallicDefault` and `roughnessDefault` into `rt/data/textures.json`
and **ignores `surface` entirely** -- so the classification is already being
authored and was simply going unused by anything.

This script is READ-ONLY on all of it. It never writes a label file, never edits
`textures.json`, and never touches `apply_material_labels.py`. It only reads the
`surface` values and emits a separate, game-readable table that `rt_sparks.cpp`
loads. If the labelling pipeline changes shape, this breaks loudly here rather
than corrupting anything upstream.

    python tools/build_spark_surfaces.py
    python tools/build_spark_surfaces.py --dry-run

WHY A SEPARATE FILE RATHER THAN READING THE LABELS DIRECTLY. The label files live
in `tools/`, which is not in the engine's lump search path -- the game cannot see
them at all. Something has to copy the data into `rt/data/`, so it may as well
arrive in the shape the loader wants: two columns, no JSON parser needed in the
renderer, diffable, and hand-editable when you want to override one texture
without re-running the labeller.

WRITE BOTH TREES. Same rule `apply_material_labels.py` documents: RTGL1 reads out
of the gitignored engine build directory, while `Retribution-RT-Materials` is the
tracked copy `build-gzdoom-rt.cmd` restages from. Writing only one means the
change either dies at the next build or never reaches the game.
"""
from pathlib import Path
import argparse
import glob
import json
import sys

PROJ_ROOT = Path(__file__).resolve().parents[1]

LABEL_DIR = PROJ_ROOT / "tools" / "_material_labels"

TARGETS = [
    PROJ_ROOT / "sourcecode" / "gzdoom-rt" / "build" / "RelWithDebInfo" / "rt" / "data" / "spark_surfaces.txt",
    PROJ_ROOT / "Doom64-Retribution" / "Retribution-RT-Materials" / "rt" / "data" / "spark_surfaces.txt",
]

TEXTURES_JSON = (
    PROJ_ROOT / "Doom64-Retribution" / "Retribution-RT-Materials" / "rt" / "data" / "textures.json"
)

# Surface classes the renderer understands. Anything else in a label file is
# passed through verbatim and treated as non-metal by the engine, so a new class
# appearing upstream degrades to debris rather than to an error.
KNOWN = ("metal", "concrete", "other")

# Liquids are marked metallic for REFLECTIVITY, never because they are metal, and
# they must never spark. The liquid gate in P_LineAttack already excludes them;
# this keeps them out of the seeded fallback too, so the file never *claims* that
# water is metal and mislead the next reader.
LIQUID_PREFIXES = ("FWATER", "BLOOD", "SLIME", "NUKAGE", "LAVA", "WATER")

HEADER = """\
# Doom 64 RT -- surface class per texture, for impact sparks and wall debris.
#
# GENERATED by tools/build_spark_surfaces.py. Do not hand-edit if you intend to
# re-run it; edit the labels instead and regenerate. Hand edits ARE useful for a
# one-off override while testing -- reload in-game with the `spark_surfaces` CCMD,
# no restart and no rebuild.
#
# FORMAT: `NAME class`, one per line, case-insensitive, '#' comments. A trailing
# '*' on the name makes it a prefix (`SPACE* metal`). A bare `NAME` with no class
# means metal, for backwards compatibility with the first version of this file.
#
#   metal      -> hot SPARKS
#   concrete   -> pale grey DEBRIS
#   other      -> darker neutral DEBRIS
#   <anything> -> treated as non-metal, i.e. debris
#
# Anything NOT listed here is non-metal and gets debris when rt_spark_debris is
# on. Use `rt_spark_surface_debug 1` and shoot a wall to see what a surface is
# called and how it classified.
#
# ---------------------------------------------------------------------------
# SECTION 1 -- AUTHORED. The `surface` field from tools/_material_labels/*.json,
# which the PBR material-labelling pipeline produces and otherwise does not use.
# This is the real classification and it wins over section 2.
# ---------------------------------------------------------------------------
"""

SEED_HEADER = """
# ---------------------------------------------------------------------------
# SECTION 2 -- SEEDED FALLBACK, for textures the labeller has not reached yet.
# Every texture carrying metallicDefault >= 0.5 in rt/data/textures.json, minus
# the liquids and minus anything already authored above. It is a guess from data
# that already existed, not a classification: metallicDefault was authored for
# REFLECTIVITY. As the labelling advances these lines get superseded and this
# section shrinks.
# ---------------------------------------------------------------------------
"""


def load_labels():
    """name -> surface, from every label file. Read-only."""
    out = {}
    files = sorted(glob.glob(str(LABEL_DIR / "*.json")))
    for f in files:
        try:
            data = json.load(open(f, encoding="utf-8"))
        except Exception as e:
            print("ERROR: %s is not readable JSON: %s" % (f, e), file=sys.stderr)
            sys.exit(1)
        for name, v in data.items():
            # `__skipped` is a list and `__meta` a dict of run info -- both are
            # the labeller's own bookkeeping and are not textures.
            if name.startswith("__") or not isinstance(v, dict):
                continue
            surf = v.get("surface")
            if not surf:
                continue
            out[name.upper()] = str(surf).strip().lower()
    return out, files


def load_seed(authored):
    if not TEXTURES_JSON.is_file():
        return []
    d = json.load(open(TEXTURES_JSON, encoding="utf-8"))
    names = []
    for t in d.get("array", []):
        n = t.get("textureName")
        if not n or float(t.get("metallicDefault", 0)) < 0.5:
            continue
        if n.upper() in authored:
            continue
        if any(n.upper().startswith(p) for p in LIQUID_PREFIXES):
            continue
        names.append(n)
    return sorted(set(names))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    authored, files = load_labels()
    seed = load_seed(authored)

    counts = {}
    for s in authored.values():
        counts[s] = counts.get(s, 0) + 1

    width = max([len(n) for n in authored] + [len(n) for n in seed] + [8]) + 2

    lines = [HEADER]
    for name in sorted(authored):
        lines.append("%-*s %s" % (width, name, authored[name]))
    lines.append(SEED_HEADER)
    for name in seed:
        lines.append("%-*s %s" % (width, name, "metal"))
    text = "\n".join(lines) + "\n"

    print("label files : %d (%s)" % (len(files), ", ".join(Path(f).name for f in files)))
    print("authored    : %d  %s" % (len(authored), counts))
    unknown = sorted({s for s in authored.values() if s not in KNOWN})
    if unknown:
        print("NOTE: classes the renderer does not know, treated as debris: %s" % unknown)
    print("seeded      : %d (metallicDefault >= 0.5, not authored, not liquid)" % len(seed))

    if args.dry_run:
        print("--dry-run: nothing written")
        return

    for t in TARGETS:
        if not t.parent.is_dir():
            print("skip (no dir): %s" % t)
            continue
        t.write_text(text, encoding="utf-8")
        print("wrote %s" % t)


if __name__ == "__main__":
    main()
