"""Build the SFLATAP grille-glow overlay for Doom 64: Unseen Evil.

WHY. Unseen Evil's Terraformer puts SFLATAP -- Doom 64's recessed slatted
grille pane -- on 445 ceilings and floors across 37 maps: DOOM's plain CEIL3_4,
CEIL1_2 and CEIL1_3, FLAT2 once d64ue-texfix.pk3 is loaded, and DOOM's own
TLITE6_1 and TLITE6_4 ceiling LIGHT panels.  The art paints a bright white
slatted panel one per 64-unit tile.  In vanilla those rooms sit at lightlevel
176-224 and the panel reads bright; under RT, where a surface only shows the
light that reaches it, it reads as dead grey metal.

The engine already puts a real bulb under each pane (rt_ue_grille_lamps), and
that alone was reported as "zero light" -- because the pane itself did not
glow.  SFLATAS, the reference the request named, carries emissiveMult 20 from
its own _e mask and visibly glows; a pane that only casts looks unlit even
while it lights the room.

WHY AN OVERLAY AND NOT AN _e IN rt/mat.  The materials are SHARED with
Retribution, and there SFLATAP is deliberately given no emissive
(gen_world_emissives.py LAMP_FLAT_NO_EMIS): it is a grille, the base game never
lights it, and its own maps use it 33 times.  A shared _e would light it in
both games.  This overlay instead supplies a GZDoom BRIGHTMAP, which the
engine's Unseen-Evil-only brightmap fallback (rt_draw.cpp, the same path the
key trims use) turns into RT emission at rt_ue_grille_emis -- and Retribution,
which never loads it, sees nothing.

THE MASK IS CUT FROM THE MOD'S OWN ART, at 72% of the texture's peak
luminance: 248 texels, the slatted panel and nothing else, bbox 18..45 on both
axes -- the same measurement rt_lights_fixtures.cpp's SFLATAP row records for
the bulb's position.

Usage:
    py -3 tools/make_unseenevil_grille.py            # report the mask
    py -3 tools/make_unseenevil_grille.py --write    # build the pk3
Output:
    Doom64-UnseenEvil/d64ue-grille-emis.pk3
"""
from __future__ import annotations

import argparse
import io
import zipfile
from pathlib import Path
from zipfile import ZIP_DEFLATED, ZipFile

import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
MOD = ROOT / "Doom64-UnseenEvil" / "D64UnseenEvil-v1.0.3.pk3"
OUT = ROOT / "Doom64-UnseenEvil" / "d64ue-grille-emis.pk3"

SRC = "textures/d64/SFLATAP.png"
MASK_PATH = "brightmaps/d64/SFLATAP.png"
# What fraction of the texture's peak luminance counts as the lit panel. 0.72
# was measured: it isolates the slats (248 texels) and excludes the housing.
THRESHOLD = 0.72

# Short name, like the mod's own d64/ entries (`material texture "CASFL98"`):
# a 7-character basename IS the texture's name in GZDoom.
GLDEFS = '''// Doom 64: Unseen Evil -- SFLATAP grille pane brightmap.
// GENERATED by tools/make_unseenevil_grille.py. Rebuild rather than edit.
//
// Turned into RT emission by the engine's Unseen-Evil-only brightmap fallback
// at rt_ue_grille_emis; the shared rt/mat materials give this flat no _e on
// purpose, because in Retribution it is an unlit grille.
material texture "SFLATAP"
{
\tbrightmap "brightmaps/d64/SFLATAP.png"
}
'''


def cut_mask() -> tuple[bytes, dict]:
    with zipfile.ZipFile(MOD) as z:
        im = Image.open(io.BytesIO(z.read(SRC))).convert("RGBA")
    a = np.asarray(im).astype(float)
    lum = a[..., :3].mean(axis=2)
    peak = float(lum.max())
    m = (a[..., 3] > 0) & (lum >= THRESHOLD * peak)
    ys, xs = np.nonzero(m)
    stats = {
        "size": im.size, "peak": peak, "lit": int(m.sum()),
        "bbox": (int(xs.min()), int(xs.max()), int(ys.min()), int(ys.max())) if len(xs) else None,
        "centroid": (float(xs.mean()) + 0.5, float(ys.mean()) + 0.5) if len(xs) else None,
    }
    # A brightmap is a mask: white where the surface is self-lit, black elsewhere.
    out = np.zeros((im.height, im.width, 4), dtype=np.uint8)
    out[m] = (255, 255, 255, 255)
    out[~m] = (0, 0, 0, 255)
    buf = io.BytesIO()
    Image.fromarray(out, "RGBA").save(buf, "PNG", optimize=True)
    return buf.getvalue(), stats


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    args = ap.parse_args()

    png, st = cut_mask()
    print(f"{SRC}: {st['size'][0]}x{st['size'][1]}, peak lum {st['peak']:.0f}, "
          f"lit {st['lit']} texels at >= {THRESHOLD:.0%}, bbox x{st['bbox'][0]}..{st['bbox'][1]} "
          f"y{st['bbox'][2]}..{st['bbox'][3]}, centroid ({st['centroid'][0]:.2f}, {st['centroid'][1]:.2f})")
    if not args.write:
        print(f"report only; pass --write to build {OUT.name}")
        return
    with ZipFile(OUT, "w", compression=ZIP_DEFLATED) as archive:
        archive.writestr(MASK_PATH, png)
        archive.writestr("GLDEFS.grille", GLDEFS)
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
