"""Build d64ue-pickup-lights.pk3: pickup glows for Doom 64: Unseen Evil.

WHY THIS SCRIPT EXISTS. The pk3 was hand-authored and was the ONLY Unseen Evil
overlay with no generator, while `Doom64-UnseenEvil/` is gitignored -- so its
GLDEFS text lived nowhere but inside that binary, and a fresh clone lost it. The
lump below is now the source of record; the pk3 is a build artifact.

WHY GLDEFS AND NOT rt/data/textures.json. That table CAN make a sprite emit
(lightIntensity + lightColorHEX, as YKEYA0/RKEYA0/SOULA0 already do) but it is
keyed on texture name and lives in rt/data, which Retribution shares. Adding
armour glow there would silently change Retribution too. GLDEFS attaches to an
ACTOR CLASS, so these are scoped to the classes only this mod defines.

WHAT WAS ALREADY WORKING, and is deliberately not repeated here: the mod's keys
carry Light("D64_RedKey") etc. in their own state tables (zscript/items/keys.zsc)
and its BFG/plasma/rocket use A_AttachLight. Re-attaching those would double the
light, not brighten it.

WHAT WAS MISSING: every armour, health and powerup pickup. D64UE_GreenArmor,
D64UE_ArmorBonus, D64UE_Soulsphere and friends define no light at all, so under a
path tracer they sit unlit on the floor -- which is what "armor on floor not green
light" is.

THE COLOURS ARE RETRIBUTION'S OWN, and that is the whole point of the 2026-08-27
pass. Reported from play: under Unseen Evil the health bonus cast a WHITE floor
pool where Retribution casts a dark blue one, and the armour bonus was predicted --
correctly, before anyone opened this file -- to read bright green instead of a mid
green. The cause was here: these were pale, desaturated tints invented for this
overlay (health was `0.40 0.55 1.00`, i.e. 40% red and 55% green, which is a
blue-WHITE), while Retribution's D64RTR_v15.WAD GLDEFS uses saturated values whose
off-channels are exactly zero:

    pulselight HEALTHBONUS { color 0.0 0.0 0.8  size 20 secondarySize 24 interval 1.5 }
    pulselight ARMORBONUS  { color 0.0 0.6 0.0  size 20 secondarySize 24 interval 1.5 }

Both mods use the sprite names BON1/BON2 -- Unseen Evil replaces the ART, not the
names -- and rt/data/textures.json gives BON1/BON2 NO light at all (bare
`{ "textureName": "BON1D0" }` stubs), so GLDEFS is the only source and its colour is
decisive. The engine forwards it verbatim (rt_lights_sector.cpp:404-412, no tint, no
white-forcing), so what is on screen is exactly what this lump asks for.

Each colour below is taken from the Retribution light that the same `frame` binding
resolves to. SIZE IS NOT COPIED: the sizes here follow the mod's own convention (its
key lights are size 84 attenuate 1, so these sit at 32..72 by pickup importance), and
Retribution's 20/24 pulselights would make the bonuses much dimmer than this overlay
intends. Colour only.

TWO OF THESE ARE HUE FLIPS, NOT DESATURATION, and they are the judgement call in
this file. Retribution lights the invulnerability sphere GREEN (0.0 1.0 0.0) and the
blur sphere RED (1.0 0.0 0.0); this overlay had them pale blue and pale green. Matching
Retribution changes what those two pickups read AS, not merely how saturated they are.
If either looks wrong in play, keep the Unseen Evil hue and just drop its off-channels
to zero -- do not split the difference, which is how the white pool happened.

BERSERK IS LEFT ALONE: PSTR has no light binding anywhere in Retribution's GLDEFS, so
there is no reference value to copy, and 1.00 0.25 0.20 is already a saturated red
consistent with the rest of the table.

    py -3 tools/make_unseenevil_pickup_lights.py            # census: report, write nothing
    py -3 tools/make_unseenevil_pickup_lights.py --write    # build the overlay pk3
"""

import argparse
import re
import zipfile
from pathlib import Path

PROJ = Path(__file__).resolve().parent.parent
OUT = PROJ / "Doom64-UnseenEvil" / "d64ue-pickup-lights.pk3"

LUMP_NAME = "GLDEFS.d64rtpickups"

# Retribution's own values, for the census to check the lump against. Sourced from
# Doom64-Retribution/D64RTR_v15.WAD -> GLDEFS, via the frame binding each pickup uses.
# None = no Retribution binding exists for that frame (berserk).
RETRIBUTION_REFERENCE = {
    "D64RT_GreenArmor": ("GREENARMOR1/2", (0.0, 0.6, 0.0)),
    "D64RT_BlueArmor": ("BLUEARMOR1/2", (0.0, 0.1, 0.6)),
    "D64RT_ArmorBonus": ("ARMORBONUS", (0.0, 0.6, 0.0)),
    "D64RT_HealthBonus": ("HEALTHBONUS", (0.0, 0.0, 0.8)),
    "D64RT_Soul": ("SOULSPHERE", (0.0, 0.2, 1.0)),
    "D64RT_Mega": ("MEGASPHERE", (1.0, 0.9, 0.8)),
    "D64RT_Invuln": ("INVULNERABILITYSPHERE", (0.0, 1.0, 0.0)),
    "D64RT_Blur": ("BLURSPHERE1", (1.0, 0.0, 0.0)),
    "D64RT_Berserk": (None, None),
}

GLDEFS_LUMP = """\
// Doom64-RT: pickup glows for Doom 64: Unseen Evil.
//
// GENERATED by tools/make_unseenevil_pickup_lights.py -- edit the lump there, not
// here. This pk3 lives in a gitignored folder; the generator is the source of record.
//
// WHY GLDEFS AND NOT rt/data/textures.json. That table CAN make a sprite emit
// (lightIntensity + lightColorHEX, as YKEYA0/RKEYA0/SOULA0 already do) but it is
// keyed on texture name and lives in rt/data, which Retribution shares. Adding
// armour glow there would silently change Retribution too. GLDEFS attaches to an
// ACTOR CLASS, so these are scoped to the classes only this mod defines.
//
// WHAT WAS ALREADY WORKING, and is deliberately not repeated here: the mod's keys
// carry Light("D64_RedKey") etc. in their own state tables (zscript/items/keys.zsc)
// and its BFG/plasma/rocket use A_AttachLight. Re-attaching those would double the
// light, not brighten it.
//
// WHAT WAS MISSING: every armour, health and powerup pickup. D64UE_GreenArmor,
// D64UE_ArmorBonus, D64UE_Soulsphere and friends define no light at all, so under a
// path tracer they sit unlit on the floor -- which is what "armor on floor not green
// light" is.
//
// NOTE ON THE ARMOURS, corrected 2026-08-27. An earlier version of this header said
// rt/data/textures.json "only ever gave ARM1A0 an emissiveMult; a later A/B removed
// even that". That is no longer true: ARM1A0/ARM2A0 now carry lightIntensity 160/200
// with lightColorHEX 44ff88/4488ff (per-frame, 70/94 on the B frames). Texture meta is
// keyed on RENDERED NAME and this mod reuses ARM1/ARM2, so those apply here too and
// the big armours carry TWO lights -- this one and the JSON one. Retribution is the
// same (GREENARMOR1/2 plus the identical JSON rows), so it is parity, not a bug. Do
// not "fix" it by deleting one side without checking Retribution first.
//
// COLOURS ARE RETRIBUTION'S, sizes are this mod's. Reported from play 2026-08-27: the
// health bonus cast a WHITE pool here against Retribution's dark blue, and the armour
// bonus read bright green against its mid green. These were pale invented tints
// (health was 0.40 0.55 1.00 -- 40% red, 55% green, i.e. a blue-WHITE) where
// Retribution's off-channels are exactly ZERO and therefore cannot wash out. Each
// value below is the Retribution light the same `frame` binding resolves to, in
// D64RTR_v15.WAD's GLDEFS. Sizes are NOT copied -- Retribution's bonuses are
// pulselight 20/24, which would be far dimmer than this overlay intends.
//
// SIZE follows the mod's own convention. Its key lights are size 84 attenuate 1, so
// these sit at 32..72 by pickup importance rather than at a number invented here.
// A bonus should be a glint, a soulsphere should light the floor around it.
//
// INVULN AND BLUR ARE HUE FLIPS, not desaturation: Retribution lights PINV green and
// PINS red, where this overlay had them pale blue and pale green. If either reads
// wrong in play, keep the Unseen Evil hue and drop its off-channels to zero -- do not
// split the difference, which is exactly how the white pool happened.
//
// BERSERK is unchanged: PSTR has no light binding in Retribution's GLDEFS, so there is
// no reference value, and this red is already saturated.

pointlight D64RT_GreenArmor  { color 0.0 0.6 0.0  size 56  attenuate 1 }
pointlight D64RT_BlueArmor   { color 0.0 0.1 0.6  size 56  attenuate 1 }
pointlight D64RT_ArmorBonus  { color 0.0 0.6 0.0  size 32  attenuate 1 }
pointlight D64RT_HealthBonus { color 0.0 0.0 0.8  size 32  attenuate 1 }
pointlight D64RT_Soul        { color 0.0 0.2 1.0  size 72  attenuate 1 }
pointlight D64RT_Mega        { color 1.0 0.9 0.8  size 72  attenuate 1 }
pointlight D64RT_Invuln      { color 0.0 1.0 0.0  size 64  attenuate 1 }
pointlight D64RT_Blur        { color 1.0 0.0 0.0  size 56  attenuate 1 }
pointlight D64RT_Berserk     { color 1.00 0.25 0.20  size 48  attenuate 1 }

object D64UE_GreenArmor   { frame ARM1 { light D64RT_GreenArmor } }
object D64UE_BlueArmor    { frame ARM2 { light D64RT_BlueArmor } }
object D64UE_ArmorBonus   { frame BON2 { light D64RT_ArmorBonus } }
object D64UE_HealthBonus  { frame BON1 { light D64RT_HealthBonus } }
object D64UE_Soulsphere   { frame SOUL { light D64RT_Soul } }
object D64UE_Megasphere   { frame MEGA { light D64RT_Mega } }
object D64UE_InvulnSphere { frame PINV { light D64RT_Invuln } }
object D64UE_BlurSphere   { frame PINS { light D64RT_Blur } }
object D64UE_Berserk      { frame PSTR { light D64RT_Berserk } }
"""

LIGHT_RE = re.compile(
    r"^pointlight\s+(\w+)\s*\{\s*color\s+([\d.]+)\s+([\d.]+)\s+([\d.]+)\s+size\s+(\d+)",
    re.M,
)


def parse_lights(text):
    """name -> (rgb tuple, size), from the lump text."""
    out = {}
    for m in LIGHT_RE.finditer(text):
        out[m.group(1)] = (
            (float(m.group(2)), float(m.group(3)), float(m.group(4))),
            int(m.group(5)),
        )
    return out


def census(lights):
    """Report each light against Retribution's own value, and flag pale tints.

    A pale tint is the failure this file was written to fix: a colour whose SMALLEST
    channel is well above zero cannot read as its own hue under the RT dynlight
    ladder, it reads as white. Retribution's pickup colours all have a zero channel.
    """
    print(f"{'light':22} {'this lump':18} {'retribution':18}  source")
    print("-" * 78)
    bad = 0
    for name, (rgb, size) in lights.items():
        ref_name, ref_rgb = RETRIBUTION_REFERENCE.get(name, (None, None))
        here = " ".join(f"{c:.2f}" for c in rgb)
        there = " ".join(f"{c:.2f}" for c in ref_rgb) if ref_rgb else "--"
        mark = ""
        if ref_rgb is not None and tuple(round(c, 3) for c in rgb) != ref_rgb:
            mark = "  <- DIFFERS"
            bad += 1
        print(f"{name:22} {here:18} {there:18}  {ref_name or '(no binding)'}{mark}")

    print()
    # A pale tint is the failure this file fixes, but "pale" alone is not the test:
    # MEGASPHERE is 1.0 0.9 0.8 in Retribution on purpose -- a warm white IS the
    # megasphere's colour. Only flag a washed-out tint that is NOT Retribution's own,
    # or the check cries wolf on the one entry that is meant to look like that.
    pale = [
        n
        for n, (rgb, _) in lights.items()
        if min(rgb) >= 0.3
        and max(rgb) > 0
        and tuple(round(c, 3) for c in rgb) != RETRIBUTION_REFERENCE.get(n, (None, None))[1]
    ]
    if pale:
        print(
            "PALE TINTS (min channel >= 0.3, and not Retribution's own value -- "
            "these read as WHITE, not as their hue): " + ", ".join(pale)
        )
    else:
        print("No unintended pale tints: every colour is Retribution's or has a zero channel.")
    print(f"{len(lights)} lights, {bad} differing from Retribution.")
    return bad


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--write", action="store_true", help="build the overlay pk3")
    args = ap.parse_args()

    lights = parse_lights(GLDEFS_LUMP)
    if len(lights) != 9:
        raise SystemExit(f"expected 9 pointlights in the lump, parsed {len(lights)}")
    census(lights)

    if not args.write:
        print(f"\n(census only -- pass --write to build {OUT.name})")
        return

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(OUT, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr(LUMP_NAME, GLDEFS_LUMP)

    # Read it back out of the pk3 rather than trusting the write: the pk3 is the only
    # artifact, so this is what proves the generator wrote what was authored.
    with zipfile.ZipFile(OUT) as z:
        if z.namelist() != [LUMP_NAME]:
            raise SystemExit(f"{OUT.name}: unexpected entries {z.namelist()}")
        back = parse_lights(z.read(LUMP_NAME).decode("utf-8"))
    if back != lights:
        raise SystemExit(f"{OUT.name}: read-back does not match the authored lump")

    print(f"\nwrote {OUT} ({OUT.stat().st_size} bytes), {len(back)} lights verified")


if __name__ == "__main__":
    main()
