"""Pack MAP99 free-roam spawn at the wallturned diagnostic pose.

East STONE2 shell on the right, dark hall left — matches screen/wallturned.png.
"""
from __future__ import annotations

import zipfile
from pathlib import Path

ROOT = Path(r"G:\AI\Doom64-RT")
PKG = ROOT / r"tools\d64r-gallery-spawn-wallturned"
OUT_PK3 = ROOT / r"Doom64-Retribution\d64r-gallery-spawn-wallturned.pk3"

# Same pose as pack_gallery_wall_ab.py
POS_X = 8250.0
POS_Y = 3600.0
YAW = 90.0


def main() -> None:
    PKG.mkdir(parents=True, exist_ok=True)
    zs = f'''version "4.12"

// Auto-generated by pack_gallery_spawn_wallturned.py
class D64RtGallerySpawnWallturned : EventHandler
{{
	const POS_X = {POS_X};
	const POS_Y = {POS_Y};
	const YAW = {YAW};
	private bool placed;

	override void WorldLoaded(WorldEvent e)
	{{
		placed = false;
	}}

	override void WorldTick()
	{{
		if (placed || level.maptime < 5)
			return;
		Actor mo = players[consoleplayer].mo;
		if (mo == null)
			return;
		mo.SetOrigin((POS_X, POS_Y, 0), false);
		mo.SetOrigin((POS_X, POS_Y, mo.floorz), false);
		mo.angle = YAW;
		mo.pitch = 0;
		mo.vel = (0, 0, 0);
		placed = true;
		Console.Printf("D64RtGallerySpawnWallturned: wallturned (%.0f,%.0f) yaw=%.0f — free roam", POS_X, POS_Y, YAW);
	}}
}}
'''
    (PKG / "ZSCRIPT").write_text(zs, encoding="utf-8")
    (PKG / "MAPINFO").write_text(
        'GameInfo\n{\n\tAddEventHandlers = "D64RtGallerySpawnWallturned"\n}\n',
        encoding="utf-8",
    )
    if OUT_PK3.exists():
        OUT_PK3.unlink()
    with zipfile.ZipFile(OUT_PK3, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for p in PKG.iterdir():
            if p.is_file():
                zf.write(p, arcname=p.name)
    print(f"wrote {OUT_PK3}")


if __name__ == "__main__":
    main()
