"""Pack MAP99 yaw-sweep EventHandler pk3 for sky/light-leak QA.

Holds the player at a fixed gallery position, yaws 0..315 by 45°, and fires
Level.MakeScreenShot() after a short settle so DLSS-RR can converge.
"""
from __future__ import annotations

import zipfile
from pathlib import Path

ROOT = Path(r"G:\AI\Doom64-RT")
PKG = ROOT / r"tools\d64r-gallery-yaw-sweep"
OUT_PK3 = ROOT / r"Doom64-Retribution\d64r-gallery-yaw-sweep.pk3"

# Center of the pillar grid for even views every direction.
POS_X = 3920.0
POS_Y = 3500.0
ANGLES = [0, 45, 90, 135, 180, 225, 270, 315]
DWELL = 90  # ~2.6s settle per angle
SHOT_AT = 50  # screenshot this many tics after arrive


def main() -> None:
    PKG.mkdir(parents=True, exist_ok=True)
    angs = ", ".join(str(a) for a in ANGLES)
    n = len(ANGLES)
    zs = f'''version "4.12"

// Auto-generated by pack_gallery_yaw_sweep.py — do not hand-edit.
// Fixed-point yaw sweep for MAP99 sky / light-leak QA.
class D64RtGalleryYawSweep : EventHandler
{{
	const COUNT = {n};
	const DWELL = {DWELL};
	const SHOT_AT = {SHOT_AT};
	const POS_X = {POS_X};
	const POS_Y = {POS_Y};
	private int idx;
	private int wait;
	private bool done;
	private bool shot;

	static const double Yaw[] = {{ {angs} }};

	override void WorldLoaded(WorldEvent e)
	{{
		idx = 0;
		wait = 35;
		done = false;
		shot = true;
	}}

	private void HoldView(int i)
	{{
		Actor mo = players[consoleplayer].mo;
		if (mo == null)
			return;
		players[consoleplayer].camera = mo;
		mo.SetOrigin((POS_X, POS_Y, 0), false);
		mo.SetOrigin((POS_X, POS_Y, mo.floorz), false);
		mo.angle = Yaw[i];
		mo.pitch = 0;
		mo.vel = (0, 0, 0);
	}}

	override void WorldTick()
	{{
		if (done || level.maptime < 8)
			return;
		if (players[consoleplayer].mo == null)
			return;

		if (wait > 0)
		{{
			Actor mo = players[consoleplayer].mo;
			if (mo != null && idx > 0)
			{{
				mo.angle = Yaw[idx - 1];
				mo.pitch = 0;
				mo.vel = (0, 0, 0);
			}}
			if (!shot && idx > 0 && wait == (DWELL - SHOT_AT))
			{{
				level.MakeScreenShot();
				Console.Printf("D64RtYawSweepShot: %d yaw=%d", idx - 1, int(Yaw[idx - 1]));
				shot = true;
			}}
			wait--;
			return;
		}}

		if (idx >= COUNT)
		{{
			Console.Printf("D64RtYawSweep: done (%d angles)", COUNT);
			done = true;
			return;
		}}

		HoldView(idx);
		Console.Printf("D64RtYawSweep: %d yaw=%d", idx, int(Yaw[idx]));
		idx++;
		wait = DWELL;
		shot = false;
	}}
}}
'''
    (PKG / "ZSCRIPT").write_text(zs, encoding="utf-8")
    (PKG / "MAPINFO").write_text(
        'GameInfo\n{\n\tAddEventHandlers = "D64RtGalleryYawSweep"\n}\n',
        encoding="utf-8",
    )

    if OUT_PK3.exists():
        OUT_PK3.unlink()
    with zipfile.ZipFile(OUT_PK3, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for p in PKG.iterdir():
            if p.is_file():
                zf.write(p, arcname=p.name)
    print(f"wrote {OUT_PK3} ({n} angles @ {POS_X},{POS_Y})")


if __name__ == "__main__":
    main()
