"""Pack d64r-rt-sky.pk3 (night sky + moon).

The pk3 was hand-assembled until the moon arrived; it now carries a generated
texture, so it needs a builder. Run tools/gen_moon_sky.py first if MOONSKY.png
is missing.

MOONSKY_preview.png is deliberately NOT packed -- it is a brightened copy for
looking at on a monitor, and shipping it would put a second, wrong sky texture
in the archive under a name GZDoom would happily resolve.
"""
from __future__ import annotations

import zipfile
from pathlib import Path

ROOT = Path(r"G:\AI\Doom64-RT")
SRC = ROOT / r"tools\d64r-rt-sky"
OUT = ROOT / r"Doom64-Retribution\d64r-rt-sky.pk3"

NAMES = (
    "MAPINFO",
    "ZSCRIPT",
    "textures/MOONSKY.png",
    "textures/MOONDISC.png",
    # Storm sky. CLOUDV1..8 are horizontal slices through one 3D cloud volume,
    # index 1 being the cloud BASE; the engine draws each on its own disc at its
    # own altitude. Every name here is looked up BY NAME from the engine
    # (RT_DrawCloudDeck / RT_DrawLightningBolt in hw_skyportal.cpp), so the
    # names and the 1-based numbering are an interface, not a convention.
    # Generated by tools/gen_clouds.py.
    *(f"textures/CLOUDV{i}.png" for i in range(1, 9)),
    *(f"textures/BOLT{i}.png" for i in range(1, 5)),
)


def main() -> None:
    missing = [n for n in NAMES if not (SRC / n).is_file()]
    if missing:
        raise SystemExit(
            f"missing under {SRC}: {', '.join(missing)}\n"
            "(MOONSKY.png: python tools/gen_moon_sky.py)\n"
            "(CLOUDS*/BOLT*: python tools/gen_clouds.py)"
        )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(OUT, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for name in NAMES:
            zf.write(SRC / name, name)
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes): {', '.join(NAMES)}")


if __name__ == "__main__":
    main()
