"""Pack d64r-rt-sky.pk3 (per-map skies + moon + storm).

The pk3 was hand-assembled until the moon arrived; it now carries generated
textures, so it needs a builder. Run tools/gen_moon_sky.py and
tools/gen_d64_skies.py first if any of the sky PNGs are missing.

*_preview.png files are deliberately NOT packed -- they are brightened copies
for looking at on a monitor, and shipping them would put second, wrong sky
textures in the archive under names GZDoom would happily resolve.
"""
from __future__ import annotations

import zipfile
from pathlib import Path

# Repo root, derived from this file so a clone can live anywhere.
PROJ_ROOT = Path(__file__).resolve().parents[1]

ROOT = PROJ_ROOT
SRC = ROOT / r"tools\d64r-rt-sky"
OUT = ROOT / r"Doom64-Retribution\d64r-rt-sky.pk3"

# The per-map skies, generated by tools/gen_d64_skies.py from the WAD's own
# skybox rooms. Every one of these is looked up BY NAME in ZSCRIPT's SkyForMap,
# so the names here are an interface. The three families that need no generated
# art -- the animated fire skies, VOIDSKY and the plain starfield rooms -- point
# at the WAD's own textures and appear in neither list.
PER_MAP_SKIES = (
    "SKYMTNA",    # MAP02/04/05/34: starfield + the tall MOUNTA ring
    "SKYMTNB",    # MAP10/16:       MOUNTB, orange backdrop (cloud is the RT deck)
    "SKYMTNC",    # MAP12/14/30:    MOUNTC, purple backdrop (cloud is the RT deck)
    "SKYCLDPK",   # MAP09/15/18/19/20: pink overcast, projected here
    "SKYCLDBR",   # MAP17/27:       brown overcast, projected here
    "SKYSTORM",   # MAP11:          storm backdrop for the deck and the lightning
)

NAMES = (
    "MAPINFO",
    "ZSCRIPT",
    "textures/MOONSKY.png",
    "textures/MOONDISC.png",
    *(f"textures/{n}.png" for n in PER_MAP_SKIES),
    # Storm sky. CLOUDV1..8 are horizontal slices through one 3D cloud volume,
    # index 1 being the cloud BASE; the engine draws each on its own disc at its
    # own altitude. Every name here is looked up BY NAME from the engine
    # (RT_DrawCloudDeck / RT_DrawLightningBolt in hw_skyportal.cpp), so the
    # names and the 1-based numbering are an interface, not a convention.
    # Generated by tools/gen_clouds.py.
    *(f"textures/CLOUDV{i}.png" for i in range(1, 9)),
    *(f"textures/BOLT{i}.png" for i in range(1, 5)),
)


def main() -> None:
    missing = [n for n in NAMES if not (SRC / n).is_file()]
    if missing:
        raise SystemExit(
            f"missing under {SRC}: {', '.join(missing)}\n"
            "(MOONSKY.png: python tools/gen_moon_sky.py)\n"
            "(SKY*.png: python tools/gen_d64_skies.py)\n"
            "(CLOUDS*/BOLT*: python tools/gen_clouds.py)\n"
            "(MTEOR*/FRBACK*: python tools/gen_fire_sky.py)"
        )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(OUT, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for name in NAMES:
            zf.write(SRC / name, name)
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes): {', '.join(NAMES)}")


if __name__ == "__main__":
    main()
