"""Pack MAP99 orbit-inward EventHandler pk3 for center-directed GI QA.

Places the player on a ring around the gallery center, looking inward, and
screenshots each stop. Catches the 'glow toward center from every approach'
failure mode that a single center-point yaw sweep misses.
"""
from __future__ import annotations

import math
import zipfile
from pathlib import Path

ROOT = Path(r"G:\AI\Doom64-RT")
PKG = ROOT / r"tools\d64r-gallery-orbit-sweep"
OUT_PK3 = ROOT / r"Doom64-Retribution\d64r-gallery-orbit-sweep.pk3"

CENTER_X = 3920.0
CENTER_Y = 3500.0
# Stay well inside the pillar field (hall spans ~0..7800). Edge stops at r=1800
# looked down clear aisles into sky-dominated frames and poisoned the score.
RADIUS = 900.0
# Doom angle: 0=east (+x), 90=north (+y). Face toward center from each stop.
BEARINGS_DEG = [0, 45, 90, 135, 180, 225, 270, 315]
DWELL = 90
SHOT_AT = 50


def main() -> None:
    PKG.mkdir(parents=True, exist_ok=True)
    xs: list[float] = []
    ys: list[float] = []
    yaws: list[float] = []
    for b in BEARINGS_DEG:
        rad = math.radians(b)
        # Stand on the ring at bearing b from center (0=east).
        x = CENTER_X + RADIUS * math.cos(rad)
        y = CENTER_Y + RADIUS * math.sin(rad)
        # Look back at center: opposite of outward bearing.
        yaw = (b + 180.0) % 360.0
        xs.append(round(x, 1))
        ys.append(round(y, 1))
        yaws.append(yaw)

    n = len(BEARINGS_DEG)
    xs_s = ", ".join(str(v) for v in xs)
    ys_s = ", ".join(str(v) for v in ys)
    yaws_s = ", ".join(str(v) for v in yaws)

    zs = f'''version "4.12"

// Auto-generated by pack_gallery_orbit_sweep.py — do not hand-edit.
// Orbit-inward sweep for MAP99 center-directed emission GI QA.
class D64RtGalleryOrbitSweep : EventHandler
{{
	const COUNT = {n};
	const DWELL = {DWELL};
	const SHOT_AT = {SHOT_AT};
	private int idx;
	private int wait;
	private bool done;
	private bool shot;

	static const double PosX[] = {{ {xs_s} }};
	static const double PosY[] = {{ {ys_s} }};
	static const double Yaw[] = {{ {yaws_s} }};

	override void WorldLoaded(WorldEvent e)
	{{
		idx = 0;
		wait = 35;
		done = false;
		shot = true;
	}}

	private void HoldView(int i)
	{{
		Actor mo = players[consoleplayer].mo;
		if (mo == null)
			return;
		players[consoleplayer].camera = mo;
		mo.SetOrigin((PosX[i], PosY[i], 0), false);
		mo.SetOrigin((PosX[i], PosY[i], mo.floorz), false);
		mo.angle = Yaw[i];
		mo.pitch = 0;
		mo.vel = (0, 0, 0);
	}}

	override void WorldTick()
	{{
		if (done || level.maptime < 8)
			return;
		if (players[consoleplayer].mo == null)
			return;

		if (wait > 0)
		{{
			Actor mo = players[consoleplayer].mo;
			if (mo != null && idx > 0)
			{{
				mo.angle = Yaw[idx - 1];
				mo.pitch = 0;
				mo.vel = (0, 0, 0);
			}}
			if (!shot && idx > 0 && wait == (DWELL - SHOT_AT))
			{{
				level.MakeScreenShot();
				Console.Printf("D64RtOrbitSweepShot: %d yaw=%d", idx - 1, int(Yaw[idx - 1]));
				shot = true;
			}}
			wait--;
			return;
		}}

		if (idx >= COUNT)
		{{
			Console.Printf("D64RtOrbitSweep: done (%d stops)", COUNT);
			done = true;
			return;
		}}

		HoldView(idx);
		Console.Printf("D64RtOrbitSweep: %d yaw=%d pos=(%.0f,%.0f)", idx, int(Yaw[idx]), PosX[idx], PosY[idx]);
		idx++;
		wait = DWELL;
		shot = false;
	}}
}}
'''
    (PKG / "ZSCRIPT").write_text(zs, encoding="utf-8")
    (PKG / "MAPINFO").write_text(
        'GameInfo\n{\n\tAddEventHandlers = "D64RtGalleryOrbitSweep"\n}\n',
        encoding="utf-8",
    )

    if OUT_PK3.exists():
        OUT_PK3.unlink()
    with zipfile.ZipFile(OUT_PK3, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for p in PKG.iterdir():
            if p.is_file():
                zf.write(p, arcname=p.name)
    print(f"wrote {OUT_PK3} ({n} inward stops, r={RADIUS} around {CENTER_X},{CENTER_Y})")


if __name__ == "__main__":
    main()
